### ISSUE TITLE
make latexpdf error

### ISSUE THREAD

**Issue by seven-tan** [lzjqsdd/scikit-learn-doc-cn#48]
/scikit-learn-doc-cn-master/doc/sphinxext/gen_rst.py", line 676, in make_thumbnail
    import Image
ImportError: No module named Image

**Comment by minoriwww** [comment]
according to:
http://pillow.readthedocs.io/en/3.1.x/installation.html#installation

"Pillow >= 1.0 no longer supports “import Image”. Please use “from PIL import Image” instead"
"Pillow >= 2.1.0 no longer supports “import _imaging”. Please use “from PIL.Image import core as _imaging” instead."  
hope it helps

**Comment by seven-tan** [comment]
thanks
